### ISSUE TITLE
데이터베이스 ERD

### ISSUE THREAD

**Issue by sss5793** [woowa-techcamp-2020/hkb-12#14]
- 데이터베이스 ERD에 대하여 공부합니다.
- 데이터베이스를 ERD로 다시 설계하고 다이어그램을 그려봅니다.

**Comment by maeng2418** [comment]
[
<img width="1083" alt="스크린샷 2020-07-28 오후 3 21 11" src="https://user-images.githubusercontent.com/46251629/88626917-698b1700-d0e6-11ea-89f3-782bd927ac03.png">
](url)

**Comment by maeng2418** [comment]
<img width="1064" alt="스크린샷 2020-07-28 오후 4 21 51" src="https://user-images.githubusercontent.com/46251629/88642771-dceb5380-d0fb-11ea-871e-4461b7cd78c4.png">
